baseURL = "https://sitkinfamily.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Love and Hot Chocolate"

[Params]
    Subtitle = "The 100 year (and counting) Tale of Gussie Paster Sitkin"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files